dist : trusty

language: ruby
rvm:
  - 2.3.3

git:
  depth: 3

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
cache: bundler

script:
  - bundle exec jekyll build && bundle exec htmlproofer --assume-extension ./_site  --disable-external

sudo: false
