# Site
remote_theme: iwiedenm/jekyll-theme-massively-src

title:              Fifty Stories Later
bio:                'Senior manager at OICR. Best things in life: bioinformatics, software dev, knitting, writing & dragons'
description:        "Morgan Taschuk"
locale:             en_US


# Social
analytics-id:       "default"
twitter:            morgantaschuk
github:             morgantaschuk

# personal
location:           Toronto, ON


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - developer-docs.md
  - CNAME
  - drafts
